@baseUrl = http://localhost:5187

GET {{baseUrl}}/health

###

POST {{baseUrl}}/webhook/whatsapp
Content-Type: application/json

{
  "event_type": "message_received",
  "data": {
    "id": "wamid.sample-001",
    "from": "526221524507@c.us",
    "body": "Hola spike",
    "fromMe": false
  }
}

###

POST {{baseUrl}}/webhook/whatsapp?from=526221524507@c.us&body=hola-desde-query&id=query-001

###

POST {{baseUrl}}/polling/run-once
